export const ADD_USER_SUCCESS="ADD_USER_SUCCESS"
export const ADD_USER_FAIL="ADD_USER_FAIL"
export const GET_CURRENT_SUCCESS="GET_CURRENT_SUCCESS"
export const GET_CURRENT_FAIL="GET_CURRENT_FAIL"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const EDIT="EDIT"
export const EDIT_FAIL="EDIT_FAIL"
export const LOGOUT="LOGOUT"
export const  naviagte="navigate"
export const GET_ALLUSERS_SUCCESS="GET_ALLUSERS_SUCCESS"
export const GET_ALLUSERS_FAIL="GET_ALLUSERS_FAIL"

export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAIL = "VERIFY_EMAIL_FAIL";