export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const GET_ONEPRODUCT_SUCCESS = "GET_ONEPRODUCT_SUCCESS";
export const GET_ONEPRODUCT_FAIL = "GET_ONEPRODUCT_FAIL";
export const SEARCHPRDT = "SEARCHPRDT";

export const DELETE_ONEPRODUCT_SUCCESS = "DELETE_ONEPRODUCT_SUCCESS";
export const DELETE_ONEPRODUCT_FAIL = "DELETE_ONEPRODUCT_FAIL";
 