export const SAVE_INVOICE_LOADING = "SAVE_INVOICE_LOADING";
export const SAVE_INVOICE_SUCCESS = "SAVE_INVOICE_SUCCESS";
export const SAVE_INVOICE_FAIL = "SAVE_INVOICE_FAIL";
export const GET_INVOICES_FAIL = "GET_INVOICES_FAIL";
export const GET_INVOICES_LOADING = "GET_INVOICES_LOADING";
export const GET_INVOICES_SUCCESS = "GET_INVOICES_SUCCESS";

